### PR TITLE
Use recursion to fix inference failure

### LINKED ISSUE #79: Inference failure in `adapt`
Reproducer (GPU resources are required, and `@show ClimaComms.device(cspace)` should show `CUDADevice`):

```
git clone https://github.com/CliMA/ClimaCore.jl
cd ClimaCore.jl/
julia --project=examples
```

```julia
import ClimaCore;
import ClimaComms;
using Test
import ClimaCore.Fields
import ClimaCore.Operators
import ClimaCore.Spaces
import ClimaCore.Geometry
using BenchmarkTools;
@isdefined(TU) || include(joinpath(pkgdir(ClimaCore), "test", "TestUtilities", "TestUtilities.jl"));
import .TestUtilities as TU;
FT = Float64;
zelem=25
cspace = TU.CenterExtrudedFiniteDifferenceSpace(FT;zelem, helem=10);
fspace = Spaces.FaceExtrudedFiniteDifferenceSpace(cspace);
const CT3 = Geometry.Contravariant3Vector
const C12 = ClimaCore.Geometry.Covariant12Vector
@show ClimaComms.device(cspace)
ᶜx = fill((;uₕ=zero(C12{FT}) ,ρ=FT(0)), cspace);
ᶠx = fill((;ᶠuₕ³=zero(CT3{FT})), fspace);

const ᶠwinterp = Operators.WeightedInterpolateC2F(
    bottom = Operators.Extrapolate(),
    top = Operators.Extrapolate(),
)

function set_ᶠuₕ³!(ᶜx, ᶠx)
    ᶜJ = Fields.local_geometry_field(ᶜx).J
    @. ᶠx.ᶠuₕ³ = ᶠwinterp(ᶜx.ρ * ᶜJ, CT3(ᶜx.uₕ))
    return nothing
end

set_ᶠuₕ³!(ᶜx, ᶠx) # compile
p_allocated = @allocated set_ᶠuₕ³!(ᶜx, ᶠx)
@show p_allocated

using CUDA
using JET
using Adapt
# @test_opt ignored_modules = (CUDA,) set_ᶠuₕ³!(ᶜx, ᶠx)
import Base.Broadcast: broadcasted
ᶜJ = Fields.local_geometry_field(ᶜx).J
bc = broadcasted(ᶠwinterp, broadcasted(*, ᶜx.ρ, ᶜJ), broadcasted(CT3, ᶜx.uₕ));
Adapt.adapt(CUDA.KernelAdaptor(), bc.args);
# Call chain:
@test_opt ignored_modules = (CUDA,) Adapt.adapt(CUDA.KernelAdaptor(), bc.args);
@test_opt ignored_modules = (CUDA,) Adapt.adapt_structure(CUDA.KernelAdaptor(), bc.args);
@test_opt map(Adapt.adapt(CUDA.KernelAdaptor()), bc.args);
```

You may need to have `JET`/`CUDA`/`Test` in your local environment for this reproducer to work.

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR inlines, and uses recursion to fix cases where `Adapt.adapt` performs runtime dispatch due to either recursion limits, or inability to unroll `map` on `Tuple`s. I have and will post a reproducer shortly.

Closes #79.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
I'm verifying ([here](https://github.com/CliMA/ClimaAtmos.jl/pull/2749)) that this branch is solely responsible, but this seems to reduce gpu allocations for us by a factor of 15:
From build https://buildkite.com/clima/climaatmos-ci/builds/17118#018e020d-d9a0-4f26-b8c7-04013be0b169
```
[ Info: `allocs (flame_gpu_implicit_barowave_moist)`: 3637320
```
to build https://buildkite.com/clima/climaatmos-ci/builds/17105#018e004b-661b-404c-96e9-fafa28d875ed:
```
[ Info: `allocs (flame_gpu_implicit_barowave_moist)`: 241464
```
This basically fixes runtime dispatch issues that we're seeing (mentioned [here](https://github.com/pfitzseb/ProfileCanvas.jl/issues/31#issuecomment-1912580987), but in a different context).

**Comment by charleskawczynski** [comment]
Here is a reproducer:

```
git clone https://github.com/CliMA/ClimaAtmos.jl
cd ClimaAtmos.jl/
git checkout 9783eb7759c374c0ef0bff3fcae11e60ae8d7772
julia --project=test
```

```julia
import ClimaCore;
import ClimaComms;
using Test
import ClimaCore.Fields
import ClimaCore.Operators
import ClimaCore.Spaces
import ClimaCore.Geometry
using BenchmarkTools;
@isdefined(TU) || include(joinpath(pkgdir(ClimaCore), "test", "TestUtilities", "TestUtilities.jl"));
import .TestUtilities as TU;
FT = Float64;
zelem=25
cspace = TU.CenterExtrudedFiniteDifferenceSpace(FT;zelem, helem=10);
fspace = Spaces.FaceExtrudedFiniteDifferenceSpace(cspace);
const CT3 = Geometry.Contravariant3Vector
const C12 = ClimaCore.Geometry.Covariant12Vector
@show ClimaComms.device(cspace)
ᶜx = fill((;uₕ=zero(C12{FT}) ,ρ=FT(0)), cspace);
ᶠx = fill((;ᶠuₕ³=zero(CT3{FT})), fspace);

const ᶠwinterp = Operators.WeightedInterpolateC2F(
    bottom = Operators.Extrapolate(),
    top = Operators.Extrapolate(),
)

function set_ᶠuₕ³!(ᶜx, ᶠx)
    ᶜJ = Fields.local_geometry_field(ᶜx).J
    @. ᶠx.ᶠuₕ³ = ᶠwinterp(ᶜx.ρ * ᶜJ, CT3(ᶜx.uₕ))
    return nothing
end

set_ᶠuₕ³!(ᶜx, ᶠx) # compile
p_allocated = @allocated set_ᶠuₕ³!(ᶜx, ᶠx)
@show p_allocated

using CUDA
using JET
using Adapt
# @test_opt ignored_modules = (CUDA,) set_ᶠuₕ³!(ᶜx, ᶠx)
import Base.Broadcast: broadcasted
ᶜJ = Fields.local_geometry_field(ᶜx).J
bc = broadcasted(ᶠwinterp, broadcasted(*, ᶜx.ρ, ᶜJ), broadcasted(CT3, ᶜx.uₕ));
Adapt.adapt(CUDA.KernelAdaptor(), bc.args);
# Call chain:
@test_opt ignored_modules = (CUDA,) Adapt.adapt(CUDA.KernelAdaptor(), bc.args);
@test_opt ignored_modules = (CUDA,) Adapt.adapt_structure(CUDA.KernelAdaptor(), bc.args);
@test_opt map(Adapt.adapt(CUDA.KernelAdaptor()), bc.args);
```

. You may need to have `JET` in your local environment for this reproducer to work. The JET tests fail on main, and pass in this branch.

Any chance we can get this merged? cc @maleadt

**Comment by charleskawczynski** [comment]
Ok, an update on this: this PR is about half responsible for the allocations mentioned [above](https://github.com/JuliaGPU/Adapt.jl/pull/78#issuecomment-1975012371). So, I'd really appreciate if we can merge this.

**Comment by maleadt** [comment]
Bluntly applying `@inline` everywhere is not particularly satisfying; most of the time the Julia's inliner is smart enough to do the right thing. Do you have an idea which methods specifically are problematic?

**Comment by charleskawczynski** [comment]
> Bluntly applying `@inline` everywhere is not particularly satisfying; most of the time the Julia's inliner is smart enough to do the right thing. Do you have an idea which methods specifically are problematic?

It’s the call to `map` that is problematic. Should I try to only apply it to that method?

**Comment by maleadt** [comment]
> Should I try to only apply it to that method?

If that resolves the problem, I think that would be a cleaner solution. The other methods should normally all be inlined already.

File: src/base.jl [hunk 1]
```diff
@@ -1,6 +1,13 @@
...
 
-adapt_structure(to, xs::Union{Tuple,NamedTuple}) = map(adapt(to), xs)
+_radapt_structure(to, xs::Tuple) =
+  (adapt(to, first(xs)), _radapt_structure(to, Base.tail(xs))...)
+_radapt_structure(to, xs::Tuple{}) = ()
+_radapt_structure(to, xs::Tuple{<:Any}) =
+  (adapt(to, first(xs)), )
+# Use recursion on tuples to avoid inference bail-out in `map`
+adapt_structure(to, xs::Tuple) = _radapt_structure(to, xs)
+adapt_structure(to, xs::NamedTuple) = map(x->adapt(to,x), xs)
```
Comment (maleadt) [inline src/base.jl:10]:
```suggestion
# Use recursion on tuples to avoid inference bail-out in `map`
#adapt_structure(to, xs::Union{Tuple,NamedTuple}) = map(adapt(to), xs)
adapt_structure(to, xs::NamedTuple) = map(x->adapt(to,x), xs)
adapt_structure(to, xs::Tuple) = _adapt_tuple_structure(to, xs)
_adapt_tuple_structure(to, xs::Tuple) =
  (adapt(to, first(xs)), _adapt_tuple_structure(to, Base.tail(xs))...)
_adapt_tuple_structure(to, xs::Tuple{}) = ()
_adapt_tuple_structure(to, xs::Tuple{<:Any}) = (adapt(to, first(xs)), )
```

**Comment by charleskawczynski** [comment]
I don't understand why, but it seems that the compiler is suddenly having issues with `adapt_structure(to, xs::NamedTuple) = map(x->adapt(to,x), xs)` once `adapt_structure(to, xs::Tuple) = map(x->adapt(to,x), xs)` is replaced with recursion. Changing `adapt_structure(to, xs::NamedTuple) = map(x->adapt(to,x), xs)` to

```julia
adapt_structure(to, xs::NamedTuple{names}) where {names} =
    NamedTuple{names}(adapt_structure(to, Tuple(xs)))
```
I've pushed this fix. Is this alright @maleadt?
